version: '3.9'

services:
    mongo_db:
        container_name: db_container
        image: mongo:latest
        #volumes:
            #- mongo_db:/data/db
        restart: always
        #ports:
            #- "27017:27017" 
        
# NOTE:  When containers start, docker-compose creates a network to which all containers join and thus all containers can communicate
    
    api:
        build: .
        ports:
            - 4000:3000 
        environment:
          PORT: 3000
          MONGODB_URI: mongodb://mongo_db:27017
          DB_NAME: my_db
          NAME: AlexMichael

        depends_on:
            - mongo_db
  
volumes:
  mongo_db: {}